### ISSUE TITLE
Distro versions with '*' not working?

### ISSUE THREAD

**Issue by Rayman** [ros/rosdistro#18406] opened 2018-07-10 08:40 UTC
Hey, I tried to depend on `python-seaborn` in my package, but I got the following error. Are distro versions with a '*' supported? Because it doesn't work for me:
```sh
$ rosdep resolve python-seaborn
```
```
No definition of [python-seaborn] for OS version [xenial]
	rosdep key : python-seaborn
	OS name    : ubuntu
	OS version : xenial
	Data: arch:
- python2-seaborn
debian:
- python-seaborn
fedora:
  pip:
    packages:
    - seaborn
gentoo:
- dev-python/seaborn
ubuntu:
  '*':
  - python-seaborn
  trusty:
    pip:
      packages:
      - seaborn

```
```
rosdep --version
0.11.8
```

**Comment by mikaelarguedas** [comment] 2018-07-10 08:46
This look like a duplicate of https://github.com/ros/rosdistro/issues/18152
Have you tried updating rosdep?
You need at least version 0.12.0 to parse these rules

**Comment by tfoote** [comment] 2018-07-10 22:11
Closing as duplicate of #18152 upgrading rosdep should resolve the issue.

**Closed by tfoote** 2018-07-10 22:11 UTC
