### ISSUE TITLE
Premature mumber 'control.tar.xz' before 'control.tar.gz'

### ISSUE THREAD

**Issue by ziangliuusc** [ros/rosdistro#19481] opened 2018-11-16 01:49 UTC
I'm tring to install ROS on my Ubuntu 14.04LTS, but the rosdistro package seems unable to be installed. The error message is as following:  

dpkg-deb: error: archive '/var/cache/apt/archives/python-rosdistro-modules_0.7.0-1_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/python-rosdistro-modules_0.7.0-1_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: archive '/var/cache/apt/archives/python-rosdistro_0.7.0-100_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/python-rosdistro_0.7.0-100_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2

Is it a issue with the packages or with my system? Newbie to Linux and ROS, it been painful trying to get everything to work. I have Linux Kernel 4.2.1 and Python 2.7 installed.

**Comment by tfoote** [comment] 2018-11-16 22:00
This is a regression due to the package being built with a newer version of the debian package format that trusty doesn't know about. 

@dirk-thomas @nuclearsandwich FYI it looks like we didn't use the older format for this latest release.

**Comment by tfoote** [comment] 2018-11-16 22:05
Actually sorry, the fix for this has been backported to trusty. You need to make sure that you have the latest version of dpkg. https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627/comments/19

https://github.com/ros-infrastructure/ros_buildfarm/pull/564

**Closed by tfoote** 2018-11-16 22:05 UTC
Labels: critical, indigo

**Comment by ziangliuusc** [comment] 2018-11-16 23:05
Okay thank you!

**Comment by knorth55** [comment] 2018-11-29 11:37
Currently, `trusty-security` stops at `1.17.5ubuntu5.6`.

```bash
$ apt-cache policy dpkg
dpkg:
  Installed: 1.17.5ubuntu5.8
  Candidate: 1.17.5ubuntu5.8
  Version table:
 *** 1.17.5ubuntu5.8 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.17.5ubuntu5.6 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     1.17.5ubuntu5 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```
In order to install `dpkg` `1.17.5ubuntu5.8`, you need to enable `trusty-updates`
![screenshot from 2018-11-29 20 33 38](https://user-images.githubusercontent.com/9300063/49219353-535f1c00-f416-11e8-9f98-b58d7718f7b6.png)
