### ISSUE TITLE
Homebrew issue on macOS High Sierra (10.13.1 17B1003).

### ISSUE THREAD

**Issue by lizixroy** [ros/rosdistro#16953] opened 2018-02-11 22:39 UTC
Hi folks,

I have been trying to install ROS on my Mac running macOS High Sierra (10.13.1 17B1003)., it's not going well. I know that MacOS is an officially supported OS, but it would be so nice if we can get this to work, because there are so many Mac users interested in leveraging ROS. 

The issue I'm getting is with rosdep, it fails on a homebrew command: 
```
ERROR: the following rosdeps failed to install
  homebrew: command [brew install ros/kinetic/gazebo_ros_pkgs] failed
```

After going through rosdep source code, I found that the way that the name of homebrew formulae are created might not work anymore. In get_gbprepo_as_rosdep_data method in gbpdistro_support.py, name of a formula is created by chaining together tap, release name and rosdep_key:
`homebrew_name = '%s/%s/%s' % (tap, release_name, rosdep_key)`
After that, 'brew install' is called with this homebrew_name: 
`executing command [brew install ros/kinetic/gazebo_ros_pkgs]`

However homebrew doesn't work with "ros/kinetic/gazebo_ros_pkgs":

```
Error: No available formula with the name "ros/kinetic/gazebo_ros_pkgs" 
Please tap it and then try again: brew tap ros/kinetic
executing command [brew install ros/kinetic/gazebo_ros_pkgs]
==> Tapping ros/kinetic
Cloning into '/usr/local/Homebrew/Library/Taps/ros/homebrew-kinetic'...
remote: Repository not found.
fatal: repository 'https://github.com/ros/homebrew-kinetic/' not found
Error: Failure while executing: git clone https://github.com/ros/homebrew-kinetic /usr/local/Homebrew/Library/Taps/ros/homebrew-kinetic --depth=1
ERROR: the following rosdeps failed to install
```

This renders resdep not functioning on macOS.

Any idea why this is happening?

Have you guys stopped supporting homebrew?

It's totally OK if I myself need to take time to make ROS installation on Mac work again, just need some pointers.

Thanks much for your time!

Roy

**Comment by wjwwood** [comment] 2018-02-13 05:03
Please don't cross post, thanks!

Closing as a duplicate of https://github.com/ros-infrastructure/rosdep/issues/586.

**Closed by wjwwood** 2018-02-13 05:03 UTC
