### ISSUE TITLE
Debian stretch rosdep key should resolve to gazebo9?

### ISSUE THREAD

**Issue by dpkoch** [ros/rosdistro#22360] opened 2019-09-24 20:37 UTC
The rosdep key `gazebo` currently resolves to `gazebo7` for Debian Stretch ([source](https://github.com/ros/rosdistro/blob/7c6449ea1e505778014dee806c8f9d22578c05f0/rosdep/base.yaml#L886)). I'll admit that my picture of everything involved is incomplete, but it seems to me that it would make more sense for it to resolve to `gazebo9`. My reasoning follows:

This issue is coming up because I have a package (rosflight_sim) that depends on Gazebo, using the `gazebo` rosdep key. I have been unable to release this package for melodic because the prerelease test fails for debian stretch, since it tries to use Gazebo 7, but melodic requires Gazebo 9 (according to [REP 3](https://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023)) and so conflicts arise. More details on the errors I'm getting are in my related post at [answers.ros.org](https://answers.ros.org/question/332846/buildfarm-melodic-debian-stretch-gazebo-unmet-dependency/).

Now, I could resolve this by creating a separate branch for melodic that depends on `gazebo9` explicitly instead of just `gazebo`. However, this seems silly, since that would be the only difference in the code base from the kinetic version (we handle the API differences with some preprocessor directives). In addition, simply depending on `gazebo` works for both kinetic and melodic on Ubuntu (resolves to `gazebo7` on xenial, and `gazebo9` on bionic), so it would be nice if the Debian rosdep keys worked in the same way.

Is the reason that Debian stretch resolves to `gazebo7` instead of `gazebo9` because the Debian repositories only contain Gazebo 7? That makes sense, but it also seems to violate the guidelines in [REP 3](https://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023) that requires Gazebo 9 support on Debian stretch. And isn't Gazebo 9 provided by the ROS sources, which are an approved source for rosdep keys according to the contribution guidelines?

Sorry for being long-winded, but the bottom line is: for the reasons above, should the `gazebo` rosdep key resolve to `gazebo9` for Debian Stretch, instead of `gazebo7`?

Thanks!

**Comment by clalancette** [comment] 2019-09-25 13:11
There's a long-standing pull request discussing this: https://github.com/ros/rosdistro/pull/19843 .  In particular, see https://github.com/ros/rosdistro/pull/19843#issuecomment-452395275 , which describes how we arrived at the current situation.  I'm going to close this out as a duplicate of that PR, but feel free to continue commenting (preferably on the PR).

**Closed by clalancette** 2019-09-25 13:11 UTC
