### ISSUE TITLE
MacOS Sierra - Incompatible OpenCV Version in Kinetic

### ISSUE THREAD

**Issue by igilitschenski** [ros/rosdistro#13298] opened 2016-11-25 09:19 UTC
When installing kinetic on MacOS Sierra, the compilation of opencv3 fails with the error `'QTKit/QTKit.h' file not found` (as Apple has removed this in the new macOS). This seems to be known (see e.g. homebrew/homebrew-science#4104, opencv/opencv#6913) and resolved by opencv/opencv#7159 which is merged in opencv master. However, this fix seems to not have made it into ROS yet. What would be the best way to incorporate it?

**Comment by tfoote** [comment] 2016-11-26 19:22
Please make a request on the packaging repo for opencv3: https://github.com/ros-gbp/opencv3-release/issues to make a new release.

**Comment by tfoote** [comment] 2016-11-28 18:35
Closing as duplicate of https://github.com/ros-gbp/opencv3-release/issues/6

**Closed by tfoote** 2016-11-28 18:35 UTC
